version: '3'

services:
  postgres:
    image: 'postgres:16'
    restart: on-failure
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'
    networks:
      - examia
    volumes:
      - 'examia-postgres:/var/lib/postgresql/data'

networks:
  examia:
    driver: bridge

volumes:
  examia-postgres:
    driver: local